name: Update MongoDB Atlas

on:
  push:
    branches:
      - main

jobs:
  update-mongodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pymongo

    - name: Update MongoDB
      run: python update_mongodb.py
      env:
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
