services:
- type: web
  name: tammy-hartlines-capstone-project
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  repo: https://github.com/tjhartline/capstone
  branch: master
  rootDir: capstone
  
